// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('@arco-design/web-vue')['Affix']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    APageHeader: typeof import('@arco-design/web-vue')['PageHeader']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
